version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
     - yarn install
 build:
   commands:
     - npm run build
     - npm run deployDashboards
     - npm run deploySimplicity
 post_build:
   commands:
     - echo "post_build step"